In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3172, 2830, 3615, 8017],
 [3172, 2830, 3615, 8051],
 [3172, 1714, 3615, 9558],
 [3158, 7984, 7796, 6140, 8816],
 [3158, 7984, 7796, 6140, 5519],
 [7834, 3172, 9419, 3615, 3797],
 [2635, 4748, 3404, 6140]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3172 2830 3615 8017]
 [   0    0    0    0 3172 2830 3615 8051]
 [   0    0    0    0 3172 1714 3615 9558]
 [   0    0    0 3158 7984 7796 6140 8816]
 [   0    0    0 3158 7984 7796 6140 5519]
 [   0    0    0 7834 3172 9419 3615 3797]
 [   0    0    0    0 2635 4748 3404 6140]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\meherdhi\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[[ 6.01351261e-04,  2.92340256e-02,  2.59028338e-02,
         -3.17487270e-02, -4.38124649e-02,  4.30879034e-02,
         -1.52413920e-03, -2.01026350e-03, -1.24785081e-02,
         -1.58902034e-02],
        [ 6.01351261e-04,  2.92340256e-02,  2.59028338e-02,
         -3.17487270e-02, -4.38124649e-02,  4.30879034e-02,
         -1.52413920e-03, -2.01026350e-03, -1.24785081e-02,
         -1.58902034e-02],
        [ 6.01351261e-04,  2.92340256e-02,  2.59028338e-02,
         -3.17487270e-02, -4.38124649e-02,  4.30879034e-02,
         -1.52413920e-03, -2.01026350e-03, -1.24785081e-02,
         -1.58902034e-02],
        [ 6.01351261e-04,  2.92340256e-02,  2.59028338e-02,
         -3.17487270e-02, -4.38124649e-02,  4.30879034e-02,
         -1.52413920e-03, -2.01026350e-03, -1.24785081e-02,
         -1.58902034e-02],
        [-2.74669062e-02, -3.44671309e-04, -2.81926244e-03,
          1.70818307e-02,  2.92516388e-02,  1.93588473e-02,
         -2.03806516e-02, -1.94618590e-02, -3.840370

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 3172, 2830, 3615, 8017])

In [24]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None